Funds_Preset = {
    "Giant": {"Starting": 500000, "Power": 1.05, "Credit": 9, "Loans": 0},
    "Huge": {"Starting": 400000, "Power": 1.05, "Credit": 9, "Loans": 0},
    "Large": {"Starting": 300000, "Power": 1.05, "Credit": 9, "Loans": 0},
    "Medium": {"Starting": 200000, "Power": 1.045, "Credit": 8, "Loans": 0},
    "Small": {"Starting": 100000, "Power": 1.045, "Credit": 8, "Loans": 0},
    "Tiny": {"Starting": 100000, "Power": 1.04, "Credit": 7, "Loans": 0},
    "Huge In Debt": {"Starting": 400000, "Power": 1.05, "Credit": 7, "Loans": 0.8},
    "Medium In Debt": {"Starting": 200000, "Power": 1.045, "Credit": 6, "Loans": 0.7},
    "Tiny In Debt": {"Starting": 100000, "Power": 1.04, "Credit": 5, "Loans": 0.6},
}

Skills_Preset = {
    "Superior": {"Manufactoring": 90, "RnD": 90, "Admin": 90, "Marketing": 90, "Dealers": 90},
    "Extremely Advanced": {"Manufactoring": 75, "RnD": 75, "Admin": 75, "Marketing": 75, "Dealers": 75},
    "Advanced": {"Manufactoring": 60, "RnD": 60, "Admin": 60, "Marketing": 60, "Dealers": 60},
    "Average": {"Manufactoring": 45, "RnD": 45, "Admin": 45, "Marketing": 45, "Dealers": 45},
    "Slightly Behind": {"Manufactoring": 35, "RnD": 35, "Admin": 35, "Marketing": 35, "Dealers": 35},
    "Talentless": {"Manufactoring": 20, "RnD": 20, "Admin": 20, "Marketing": 20, "Dealers": 20},
    "Startup": {"Manufactoring": 10, "RnD": 10, "Admin": 10, "Marketing": 10, "Dealers": 10},
    "Bored 12 Years Old Kids": {"Manufactoring": 1, "RnD": 1, "Admin": 1, "Marketing": 1, "Dealers": 1}
}

Design_Preset = {
    "Superior": {"Engine": 90, "Chassis": 90, "Transmission": 90, "Body": 90, "Lux": 90, "safety": 90},
    "Extremely Advanced": {"Engine": 75, "Chassis": 75, "Transmission": 75, "Body": 75, "Lux": 75, "safety": 75},
    "Advanced": {"Engine": 60, "Chassis": 60, "Transmission": 60, "Body": 60, "Lux": 60, "safety": 60},
    "Average": {"Engine": 45, "Chassis": 45, "Transmission": 45, "Body": 45, "Lux": 45, "safety": 45},
    "Below Average": {"Engine": 30, "Chassis": 30, "Transmission": 30, "Body": 30, "Lux": 30, "safety": 30},
    "Slightly Behind": {"Engine": 20, "Chassis": 20, "Transmission": 20, "Body": 20, "Lux": 20, "safety": 20},
    "Behind": {"Engine": 10, "Chassis": 10, "Transmission": 10, "Body": 10, "Lux": 10, "safety": 10},
    "VENT": {"Engine": 5, "Chassis": 5, "Transmission": 5, "Body": 5, "Lux": 5, "safety": 5},
    "Digital Homicide Skills": {"Engine": 1, "Chassis": 1, "Transmission": 1, "Body": 1, "Lux": 1, "safety": 1},
}

Image_Preset = {
    "Adored": {"GeneralGlobal": 90, "Quality": 90, "Racing": 90, "Work": 90},
    "Loved": {"GeneralGlobal": 75, "Quality": 75, "Racing": 75, "Work": 75},
    "Pleased": {"GeneralGlobal": 50, "Quality": 50, "Racing": 50, "Work": 50},
    "Neutral": {"GeneralGlobal": 40, "Quality": 40, "Racing": 40, "Work": 40},
    "Unknown": {"GeneralGlobal": 25, "Quality": 25, "Racing": 25, "Work": 25},
    "Hated": {"GeneralGlobal": 10, "Quality": 10, "Racing": 10, "Work": 10},
    "Scum": {"GeneralGlobal": 1, "Quality": 1, "Racing": 1, "Work": 1},
}

Behavior_Preset = {
    "Generic Manufacturer": {"GenericDesigner": 1, "Rating_Performance": 0.35, "Rating_Drivability": 0.35,
                              "Rating_Luxury": 0.35, "Rating_Safety": 0.35, "Rating_Fuel": 0.35, "Rating_Power": 0.35,
                              "Rating_Cargo": 0.35, "Rating_Dependability": 0.35},
    "Upper Class Generic": {"GenericDesigner": 1, "Rating_Performance": 0.5, "Rating_Drivability": 0.5,
                              "Rating_Luxury": 0.8, "Rating_Safety": 0.8, "Rating_Fuel": 0.2, "Rating_Power": 0.7,
                              "Rating_Cargo": 0.6, "Rating_Dependability": 0.7},
    "Lower Class Generic": {"GenericDesigner": 1, "Rating_Performance": 0.1, "Rating_Drivability": 0.1,
                              "Rating_Luxury": 0.1, "Rating_Safety": 0.3, "Rating_Fuel": 0.7, "Rating_Power": 0.2,
                              "Rating_Cargo": 0.3, "Rating_Dependability": 0.4},
    "Performance Generic": {"GenericDesigner": 1, "Rating_Performance": 0.8, "Rating_Drivability": 0.6,
                              "Rating_Luxury": 0.3, "Rating_Safety": 0.3, "Rating_Fuel": 0.2, "Rating_Power": 0.8,
                              "Rating_Cargo": 0.3, "Rating_Dependability": 0.3},
    "Truck Company": {"GenericDesigner": 0, "Rating_Performance": 0.5, "Rating_Drivability": 0.1,
                              "Rating_Luxury": 0.1, "Rating_Safety": 0.2, "Rating_Fuel": 0.2, "Rating_Power": 1,
                              "Rating_Cargo": 1, "Rating_Dependability": 0.7},
    "Performance Company": {"GenericDesigner": 0, "Rating_Performance": 0.7, "Rating_Drivability": 0.3,
                              "Rating_Luxury": 0.3, "Rating_Safety": 0.3, "Rating_Fuel": 0.2, "Rating_Power": 0.6,
                              "Rating_Cargo": 0.3, "Rating_Dependability": 0.5},
    "Ultra High Rich Performance": {"GenericDesigner": 0, "Rating_Performance": 1, "Rating_Drivability": 0.8,
                              "Rating_Luxury": 0.3, "Rating_Safety": 0.1, "Rating_Fuel": 0.1, "Rating_Power": 1,
                              "Rating_Cargo" : 0.1, "Rating_Dependability": 0.1},
    "Fun Handling": {"GenericDesigner": 0, "Rating_Performance": 0.5, "Rating_Drivability": 1,
                              "Rating_Luxury": 0.1, "Rating_Safety": 0.1, "Rating_Fuel": 0.3, "Rating_Power": 0.3,
                              "Rating_Cargo": 0.1, "Rating_Dependability": 0.2},
    "Luxury Company": {"GenericDesigner": 0, "Rating_Performance": 0.4, "Rating_Drivability": 0.4,
                              "Rating_Luxury": 1, "Rating_Safety": 0.8, "Rating_Fuel": 0.3, "Rating_Power": 0.6,
                              "Rating_Cargo": 0.7, "Rating_Dependability": 0.7},
    "Economic Company": {"GenericDesigner": 0, "Rating_Performance": 0.3, "Rating_Drivability": 0.3,
                              "Rating_Luxury": 0.1, "Rating_Safety": 0.4, "Rating_Fuel": 0.8, "Rating_Power": 0.3,
                              "Rating_Cargo": 0.4, "Rating_Dependability": 0.3},
    "Micro Car Company": {"GenericDesigner": 0, "Rating_Performance": 0.05, "Rating_Drivability": 0.1,
                              "Rating_Luxury": 0.05, "Rating_Safety": 0.05, "Rating_Fuel": 0.8, "Rating_Power": 0.05,
                              "Rating_Cargo": 0.05, "Rating_Dependability": 0.5},
    "Safety First": {"GenericDesigner": 0, "Rating_Performance": 0.2, "Rating_Drivability": 0.6,
                              "Rating_Luxury": 0.4, "Rating_Safety": 1, "Rating_Fuel": 0.3, "Rating_Power": 0.3,
                              "Rating_Cargo": 0.6, "Rating_Dependability": 0.8},
    "Green": {"GenericDesigner": 0, "Rating_Performance": 0.1, "Rating_Drivability": 0.4,
                              "Rating_Luxury": 0.4, "Rating_Safety": 0.6, "Rating_Fuel": 1, "Rating_Power": 0.1,
                              "Rating_Cargo": 0.5, "Rating_Dependability": 0.5},
}

Aggressions_Preset = {
    "Passive": {"DesignAggression": 0.2, "SellAggression": 0.25, "BuildAggression": 0.2, "MarketingAggression": 0.2,
                "CostAggression": 0.4, "QualityAggression": 0.4, "PriceAggression": 0.2, "ExpansionAggression": 0.2,
                "ClusterSpace": 0.5, "ExportDesigns": 0.5, "ImportDesigns": 0.5},
    "Average": {"DesignAggression": 0.5, "SellAggression": 0.5, "BuildAggression": 0.5, "MarketingAggression": 0.5,
                "CostAggression": 0.5, "QualityAggression": 0.5, "PriceAggression": 0.5, "ExpansionAggression": 0.5,
                "ClusterSpace": 0.4, "ExportDesigns": 0.5, "ImportDesigns": 0.5},
    "Aggressive": {"DesignAggression": 0.8, "SellAggression": 0.8, "BuildAggression": 0.8, "MarketingAggression": 0.8,
                "CostAggression": 0.3, "QualityAggression": 0.3, "PriceAggression": 0.8, "ExpansionAggression": 0.8,
                "ClusterSpace": 0.3, "ExportDesigns": 0.2, "ImportDesigns": 0.8},
    "Aggressive Expansion": {"DesignAggression": 0.4, "SellAggression": 0.6, "BuildAggression": 0.8, "MarketingAggression": 0.4,
                "CostAggression": 0.3, "QualityAggression": 0.3, "PriceAggression": 0.3, "ExpansionAggression": 1,
                "ClusterSpace": 0.1, "ExportDesigns": 0.3, "ImportDesigns": 0.3},
    "Aggressive Costs": {"DesignAggression": 0.2, "SellAggression": 0.4, "BuildAggression": 0.3, "MarketingAggression": 0.4,
                "CostAggression": 0.9, "QualityAggression": 0.3, "PriceAggression": 0.6, "ExpansionAggression": 0.3,
                "ClusterSpace": 0.5, "ExportDesigns": 0.7, "ImportDesigns": 0.1},
    "Best Quality": {"DesignAggression": 0.6, "SellAggression": 0.3, "BuildAggression": 0.3, "MarketingAggression": 0.3,
                "CostAggression": 0.1, "QualityAggression": 0.9, "PriceAggression": 0.6, "ExpansionAggression": 0.3,
                "ClusterSpace": 0.3, "ExportDesigns": 0.4, "ImportDesigns": 0.05},
    "Look for Profits": {"DesignAggression": 0.4, "SellAggression": 0.7, "BuildAggression": 0.3, "MarketingAggression": 0.6,
                "CostAggression": 0.5, "QualityAggression": 0.4, "PriceAggression": 0.8, "ExpansionAggression": 0.4,
                "ClusterSpace": 0.05, "ExportDesigns": 0.8, "ImportDesigns": 0.3},
    "Close to Home": {"DesignAggression": 0.4, "SellAggression": 0.4, "BuildAggression": 0.6, "MarketingAggression": 0.3,
                "CostAggression": 0.4, "QualityAggression": 0.3, "PriceAggression": 0.4, "ExpansionAggression": 0.7,
                "ClusterSpace": 0.9, "ExportDesigns": 0.4, "ImportDesigns": 0.4},
}